### ISSUE TITLE
Strange syntax error: Am I missing something?

### ISSUE THREAD

**Issue by jgrizou** [openscad/list-comprehension-demos#2]
Hello,

I am trying to use the sweep and skin tools which look amazing. I tried the sweep-path.scad and the extrusion.scad scripts but I am having weird syntax errors. 

For example, in  sweep-path.scad, line 20: 
``` 
path = [for (t=[0:step:1-step]) f(t)]; 
```
returns a syntax error. In fact, even the sweep.scad and skin.scad are producing syntax error, always on a for loop inside brackets. I never used such syntax before but openscad is openscad, if it works for you it should work here. Are you using a different version or something?

I am using OpenSCAD version 2014.03 on MacOSX Yosemite.

Here is my repo: https://github.com/jgrizou/segment-scad, the code in dev.scad is the one that produces the syntax error. I am using scad-utils in the repo, and not in the global library folder, but this should not matter.

Regards,

**Comment by kintel** [comment]
Theis functionality is only available in the development snapshots.
