### ISSUE TITLE
$fn for sweep

### ISSUE THREAD

**Issue by tcurdt** [openscad/list-comprehension-demos#5]
I look at https://github.com/openscad/list-comprehension-demos/blob/master/sweep.scad and I am not sure how the magic works (yet) - but it certainy would be great to control the resolution of the sweep (like a $fn).

**Comment by t-paul** [comment]
This is simply controlled by the number and spacing of transformations given, e.g. the number of `for()` loops in https://github.com/openscad/list-comprehension-demos/blob/master/sweep-test.scad#L17 - it's somewhat comparable with the `slices` parameter in `linear_extrude()`.

**Comment by tcurdt** [comment]
ah! that makes sense. thanks!

**Comment by kintel** [comment]
Whenever we add support for sweeping using a parametrized path, we should probably use $fn etc. to control this.
