### ISSUE TITLE
Toothed gear example doesn't compile with lastest scad-utils 

### ISSUE THREAD

**Issue by delaneyj** [openscad/list-comprehension-demos#7]
Trying to learn about toothed gears and when I try to [run the example](https://github.com/openscad/list-comprehension-demos/blob/master/toothed-belt.scad) I get `Can't open library 'scad-utils/shapes.scad'. `  Had grabbed the lastest version of utils but looks like shapes.scad has been deprecated.

**Comment by kintel** [comment]
`scad-utils` has to be installed separately.
See README: https://github.com/openscad/list-comprehension-demos/blob/master/README.md

**Comment by delaneyj** [comment]
Sorry, had the original scad-utils, now its saying `ERROR: Recursion detected calling function 'len' `
